"""Compatibility re-exports for MARS domain objects.

Domain definitions reside in the focused ``mars.domain`` submodules.
"""

from .domain import (
    TASK_CLASS_LABELS,
    TERMINAL_STATES,
    ArtifactRef,
    Assignment,
    DataEdge,
    DataPort,
    ExecutionMode,
    FailurePolicy,
    InputArtifactBinding,
    LinkSnapshot,
    LinkSpec,
    NodeKind,
    NodeSnapshot,
    NodeSpec,
    PlacementConstraints,
    ResourceClass,
    TaskClass,
    TaskCompletion,
    TaskInstance,
    TaskSpec,
    TaskState,
    TransferEstimate,
    TransferReservation,
    WorkflowProgress,
    WorkflowSpec,
    WorkflowState,
    artifacts_from_bindings,
    infer_task_class,
    resolved_placement_constraints,
    task_resource_demand,
)

__all__ = [
    "ArtifactRef",
    "Assignment",
    "DataEdge",
    "DataPort",
    "ExecutionMode",
    "FailurePolicy",
    "InputArtifactBinding",
    "LinkSnapshot",
    "LinkSpec",
    "NodeKind",
    "NodeSnapshot",
    "NodeSpec",
    "PlacementConstraints",
    "ResourceClass",
    "TASK_CLASS_LABELS",
    "TERMINAL_STATES",
    "TaskClass",
    "TaskCompletion",
    "TaskInstance",
    "TaskSpec",
    "TaskState",
    "TransferEstimate",
    "TransferReservation",
    "WorkflowProgress",
    "WorkflowSpec",
    "WorkflowState",
    "artifacts_from_bindings",
    "infer_task_class",
    "resolved_placement_constraints",
    "task_resource_demand",
]
