# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interfaces/proto/mars/v1/artifact_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'interfaces/proto/mars/v1/artifact_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/interfaces/proto/mars/v1/artifact_service.proto\x12\x07mars.v1\"%\n\x13ReadArtifactRequest\x12\x0e\n\x06sha256\x18\x01 \x01(\t\"4\n\x14ReadArtifactResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06sha256\x18\x02 \x01(\t2\\\n\rArtifactStore\x12K\n\x0cReadArtifact\x12\x1c.mars.v1.ReadArtifactRequest\x1a\x1d.mars.v1.ReadArtifactResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interfaces.proto.mars.v1.artifact_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READARTIFACTREQUEST']._serialized_start=60
  _globals['_READARTIFACTREQUEST']._serialized_end=97
  _globals['_READARTIFACTRESPONSE']._serialized_start=99
  _globals['_READARTIFACTRESPONSE']._serialized_end=151
  _globals['_ARTIFACTSTORE']._serialized_start=153
  _globals['_ARTIFACTSTORE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
