# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from interfaces.proto.mars.v1 import runtime_pb2 as interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2
from interfaces.proto.mars.v1 import runtime_service_pb2 as interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in interfaces/proto/mars/v1/runtime_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRuntimeStub:
    """Control-plane RPC service implemented by every real agent process.

    The coordinator-side GrpcRuntimeAdapter is the client; each agent hosts this
    service. Message payloads reuse the data-only contracts in runtime.proto.
    State freshness is pull-based: the adapter calls GetState before each
    planning iteration instead of relying on agent-pushed heartbeats.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/mars.v1.AgentRuntime/RegisterAgent',
                request_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/mars.v1.AgentRuntime/GetState',
                request_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2.GetStateRequest.SerializeToString,
                response_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.DispatchTask = channel.unary_unary(
                '/mars.v1.AgentRuntime/DispatchTask',
                request_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.DispatchCommand.SerializeToString,
                response_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.DispatchAck.FromString,
                _registered_method=True)
        self.StreamCompletions = channel.unary_stream(
                '/mars.v1.AgentRuntime/StreamCompletions',
                request_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2.CompletionSubscription.SerializeToString,
                response_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.AttemptCompletion.FromString,
                _registered_method=True)
        self.CancelAttempt = channel.unary_unary(
                '/mars.v1.AgentRuntime/CancelAttempt',
                request_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.CancelAttemptRequest.SerializeToString,
                response_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.CancelAttemptResponse.FromString,
                _registered_method=True)


class AgentRuntimeServicer:
    """Control-plane RPC service implemented by every real agent process.

    The coordinator-side GrpcRuntimeAdapter is the client; each agent hosts this
    service. Message payloads reuse the data-only contracts in runtime.proto.
    State freshness is pull-based: the adapter calls GetState before each
    planning iteration instead of relying on agent-pushed heartbeats.
    """

    def RegisterAgent(self, request, context):
        """Handshake at adapter start: the request carries the NodeSpec the
        coordinator expects; the agent accepts only when its configured node_id
        matches.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Pull the agent's current dynamic state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchTask(self, request, context):
        """Commit one validated plan fragment to this agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCompletions(self, request, context):
        """Server-streaming completion feed: the agent pushes one AttemptCompletion
        per terminal attempt over a stream opened at adapter start.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAttempt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.RegisterAgentRequest.FromString,
                    response_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2.GetStateRequest.FromString,
                    response_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2.GetStateResponse.SerializeToString,
            ),
            'DispatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchTask,
                    request_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.DispatchCommand.FromString,
                    response_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.DispatchAck.SerializeToString,
            ),
            'StreamCompletions': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCompletions,
                    request_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2.CompletionSubscription.FromString,
                    response_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.AttemptCompletion.SerializeToString,
            ),
            'CancelAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAttempt,
                    request_deserializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.CancelAttemptRequest.FromString,
                    response_serializer=interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.CancelAttemptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mars.v1.AgentRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mars.v1.AgentRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRuntime:
    """Control-plane RPC service implemented by every real agent process.

    The coordinator-side GrpcRuntimeAdapter is the client; each agent hosts this
    service. Message payloads reuse the data-only contracts in runtime.proto.
    State freshness is pull-based: the adapter calls GetState before each
    planning iteration instead of relying on agent-pushed heartbeats.
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mars.v1.AgentRuntime/RegisterAgent',
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.RegisterAgentRequest.SerializeToString,
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mars.v1.AgentRuntime/GetState',
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2.GetStateRequest.SerializeToString,
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DispatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mars.v1.AgentRuntime/DispatchTask',
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.DispatchCommand.SerializeToString,
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.DispatchAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCompletions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mars.v1.AgentRuntime/StreamCompletions',
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__service__pb2.CompletionSubscription.SerializeToString,
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.AttemptCompletion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mars.v1.AgentRuntime/CancelAttempt',
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.CancelAttemptRequest.SerializeToString,
            interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2.CancelAttemptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
