# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interfaces/proto/mars/v1/runtime_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'interfaces/proto/mars/v1/runtime_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from interfaces.proto.mars.v1 import runtime_pb2 as interfaces_dot_proto_dot_mars_dot_v1_dot_runtime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.interfaces/proto/mars/v1/runtime_service.proto\x12\x07mars.v1\x1a&interfaces/proto/mars/v1/runtime.proto\"#\n\x0fGetStateRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"i\n\x10GetStateResponse\x12*\n\theartbeat\x18\x01 \x01(\x0b\x32\x17.mars.v1.AgentHeartbeat\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"*\n\x16\x43ompletionSubscription\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t2\x83\x03\n\x0c\x41gentRuntime\x12N\n\rRegisterAgent\x12\x1d.mars.v1.RegisterAgentRequest\x1a\x1e.mars.v1.RegisterAgentResponse\x12?\n\x08GetState\x12\x18.mars.v1.GetStateRequest\x1a\x19.mars.v1.GetStateResponse\x12>\n\x0c\x44ispatchTask\x12\x18.mars.v1.DispatchCommand\x1a\x14.mars.v1.DispatchAck\x12R\n\x11StreamCompletions\x12\x1f.mars.v1.CompletionSubscription\x1a\x1a.mars.v1.AttemptCompletion0\x01\x12N\n\rCancelAttempt\x12\x1d.mars.v1.CancelAttemptRequest\x1a\x1e.mars.v1.CancelAttemptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interfaces.proto.mars.v1.runtime_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATEREQUEST']._serialized_start=99
  _globals['_GETSTATEREQUEST']._serialized_end=134
  _globals['_GETSTATERESPONSE']._serialized_start=136
  _globals['_GETSTATERESPONSE']._serialized_end=241
  _globals['_COMPLETIONSUBSCRIPTION']._serialized_start=243
  _globals['_COMPLETIONSUBSCRIPTION']._serialized_end=285
  _globals['_AGENTRUNTIME']._serialized_start=288
  _globals['_AGENTRUNTIME']._serialized_end=675
# @@protoc_insertion_point(module_scope)
